variable "vpc_id" {}
variable "public_subnet_id" {}
variable "key_name" {}
variable "ami_version" {}
variable "http_ipv4_security_group" {}
variable "http_ipv6_security_group" {}
variable "ssh_ipv4_security_group" {}
variable "ssh_ipv6_security_group" {}
variable "instance_type" {}
variable "associate_public_ip_address" {}